# Интервал между сообщениями в секундах (240 = 4 минуты)
time: 240

# Сообщения для отправки в чат
# Каждый блок под номером - отдельное сообщение
# Можно создавать сколько угодно блоков
messages:
  '1':
    - '&7'
    - ' &x&F&C&7&B&0&0&lꐁ &fХотите &x&F&C&7&B&0&0&lподдержать &x&F&C&7&B&0&0&lсервер &fи получить доступ'
    - ' &x&F&C&7&B&0&0&lꐁ &fк эксклюзивным возможностям?'
    - ' &x&F&C&7&B&0&0&lꐁ &fПокупайте донат услуги на нашем &x&F&C&7&B&0&0&lсайте'
    - ' &x&F&C&7&B&0&0&lꐀ LightWorld.ru'
    - '&7'

  # Пример второго сообщения (можно добавить)
  '2':
    - '&6§l✨ Добро пожаловать на сервер!'
    - '&eИспользуйте /help для списка команд'
    - '&7'

# Звук, который будет воспроизводиться при каждом сообщении
# Chicken Plop (ENTITY_CHICKEN_EGG)
sound: ENTITY_CHICKEN_EGG